

main:
  - name: Home
    url: '#about'
    weight: 10
  - name: Dissertation
    url: dissertation/
    weight: 30
  - name: Featured Publications
    url: '#featured'
    weight: 20
  - name: CV
    url: uploads/resume.pdf    
    weight: 40
  - name: Contact
    url: '#contact'
    weight: 50
